# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c2qiXtJ772cwdgwdNuQVYgyqw3D67Ttt
"""

!pip install gradio json5 jsonschema python-dotenv pydantic

import json
import re
from enum import Enum
import gradio as gr

class CaseStyle(Enum):
    SNAKE_CASE = "snake_case"
    CAMEL_CASE = "camelCase"
    KEBAB_CASE = "kebab-case"
    PASCAL_CASE = "PascalCase"

class JSONRefinerCore:

    def __init__(self):
        self.conversion_log = []
        self.validation_errors = []
        self.transformation_history = []

    def infer_type(self, value):

        value = value.strip()

        if value.lower() in ["true","yes","on"]:
            return True

        if value.lower() in ["false","no","off"]:
            return False

        if value.lower() in ["null","none","nil"]:
            return None

        try:
            if "." in value:
                return float(value)
            return int(value)
        except:
            pass

        return value

refiner = JSONRefinerCore()

def key_value_to_json(text):

    result = {}

    lines = text.strip().split("\n")

    for line in lines:

        if ":" in line:

            key, value = line.split(":",1)

            key = key.strip()
            value = value.strip()

            value = refiner.infer_type(value)

            result[key] = value

    return result

def convert_to_json(input_text):

    result = key_value_to_json(input_text)

    return json.dumps(result, indent=4)


interface = gr.Interface(

    fn=convert_to_json,

    inputs=gr.Textbox(lines=10, placeholder="Enter key-value pairs"),

    outputs="code",

    title="JSON Refiner",

    description="Convert key-value text into JSON"

)

interface.launch()